### ISSUE TITLE
Misleading in README

### ISSUE THREAD

**Issue by yukang2017** [fudan-zvg/DeepInteraction#1]
Hi,

Thanks for sharing your great performance of this work.
A little question is why you also use the name **BEVFusion** in README?

By the way, when will you share your work on arxiv? I am looking forward to reading it!

Thanks,
Yukang Chen

**Comment by Alexander0Yang** [comment]
Sorry, typo! I just copy the table for orgnizing the README. 
We will make our work on arxiv next week. Stay tuned!
Thank you.
