### ISSUE TITLE
lost some module "mmdet3d.ops.iou3d"

### ISSUE THREAD

**Issue by CarlHuangNuc** [fudan-zvg/DeepInteraction#10]
Hi Author,

I try to reproduce this paper.
merge your code to mmdetection3d. but found "mmdet3d.ops.iou3d" lost.

Hope your can submit this part code.

**Comment by Alexander0Yang** [comment]
`mmdet3d.ops.iou3d` was removed from mmdet3d in [#1240](https://github.com/open-mmlab/mmdetection3d/pull/1240). You can run our code with the recommended version of mmdet3d in our installation instruction.
