### ISSUE TITLE
val mAP table 6

### ISSUE THREAD

**Issue by jamesgunnfiveai** [fudan-zvg/DeepInteraction#13]
Hey folks, thanks for the great work.

I'm a little confused by the results in table 6 for the DeepInteraction results on the nuscenes val split. The class-specific mAP numbers don't  seem to add up to the overall mAP.

The paper (v3: https://arxiv.org/pdf/2208.11112v3.pdf) quotes:
| BR | bicycle | bus  | car  | CV   | MT (motorcycle?)   | ped  | TC   | TL | truck | mAP  |
|---------|---------|------|------|------|------|------|------|---------|-------|------|
| 78.1    | 52.9    | 68.3 | 87.1 | 33.1 | 73.6 | 88.4 | 86.7 | 60.8    | 60.0  | 69.9 |

But if you take the average of the individual scores, the result is 68.9. Am I doing something wrong or is one of these numbers incorrect?

Thanks.

**Comment by Alexander0Yang** [comment]
sorry our mistake. The numbers are Transfusion's results. We have updated arxiv paper V4 with the correct class-specific mAP.
