### ISSUE TITLE
Performance of reproduced TransFusion-L

### ISSUE THREAD

**Issue by yichen928** [fudan-zvg/DeepInteraction#17]
Congratulation on your great work! 

I notice that you use TransFusion-L as the initialization of your network. However, the authors of TransFusion do not provide the pretrained checkpoint. Can you share the performance of your reproduced TransFusion-L on NuScenes val set?

Besides, you seem to delete the shared_conv layer in TransFusion-L in your "r50_fpn_voxel_0075.pth". Is that any motivation for this simple modification? Does it lead to better performance?

Thank you very much for your help.

**Comment by Alexander0Yang** [comment]
The mAP and NDS of reproduced Transfusion-L are 65.1 and 70.1 respectively, same as those reported in Section. F of the Transfusion paper (Supplementary Material).
Actually, I moved the shared conv layer in the encoder rather than deleting it.

**Comment by yichen928** [comment]
Thank you very much for your kind reply!
