### ISSUE TITLE
About the checkpoint Fusion_0075_refactor.pth

### ISSUE THREAD

**Issue by pyz-creeper** [fudan-zvg/DeepInteraction#19]
Thanks for your great work. I have a problem when testing DeepInteraction-base model with the given checkpoint. I got a 69.81 mAP and 60.76 NDS. I wonder why I got a very low NDS score.
The testing command is `python tools/test.py projects/configs/nuscenes/Fusion_0075_refactor.py ./pretrained/Fusion_0075_refactor.pth  --eval=bbox`.

**Comment by Alexander0Yang** [comment]
Hi @pyz-creeper.
NDS consolidates various metrics including mAP. Checking which other metrics are obviously abnormal may help you find the reason.

**Comment by pyz-creeper** [comment]
Sorry, my bad. It seems that I modified some code in my mmdetection3d environment without changing it back.
