### ISSUE TITLE
关于开源的一些小疑问 Some small questions about open source

### ISSUE THREAD

**Issue by lxy-04** [fudan-zvg/DeepInteraction#2]
嗨！请问您之后有开源`nuScenes`数据集上预训练模型和test/val检测结果的打算吗？期待您的回复 :smiley:

Hi! Do you have any plans to open-source pre-training models and detection results on the `nuScenes` test/Val set in the future?  
Looking forward to your reply. : smiley:

**Comment by Alexander0Yang** [comment]
yes
