### ISSUE TITLE
voxel_size and max_voxels

### ISSUE THREAD

**Issue by Monoclinic** [fudan-zvg/DeepInteraction#20]
Hello, thanks for your great work.
I wonder how to adjust max_voxels in the config if I want to change the voxel size.
For example if I change [0.075, 0.075, 0.2] to [0.05, 0.05, 0.2], should max_voxels be in inverse proportion to it?([120k, 160k] -> [180k, 240k])
Btw in the paper you say "the voxel size of deepinteraction-large" is set to [0.5m, 0.5m, 0.2m], I wonder if it is a typo(0.05m)?

**Comment by Alexander0Yang** [comment]
In your example, a more reasonable scale is 2.25x rather than 1.5x, or you can try the dynamic voxelization to avoid tuning it.

Yes, that is a typo. If you want to get a larger receptive field, it is better to use a deeper network rather than increasing the voxel size.

**Comment by Monoclinic** [comment]
Thanks for your reply.
