### ISSUE TITLE
RoIs for 1st MMPI-Image layer 

### ISSUE THREAD

**Issue by gopi231091** [fudan-zvg/DeepInteraction#5]
Hello,

Very interesting work!

May be I missed something, can you please clarify: how the 'N' RoI are extracted for the 1st MMPI-Image layer (in the decoder), because there are no previous predictions for the initial layer. 
Do you apply FFN layer on initialized object queries to get the predictions for 1st MMPI-Image layer ?

And, can you tentatively give any timeline for code release?

Thanks!

**Comment by Alexander0Yang** [comment]
Hi @gopi231091, 

Thank you for your interest. 

> May be I missed something, can you please clarify: how the 'N' RoI are extracted for the 1st MMPI-Image layer (in the decoder), because there are no previous predictions for the initial layer.

The initial layer is a standard Transformer decoder layer as Transfusion, which initializes both the proposal embeddings and the proposal boxes.
