### ISSUE TITLE
larger lidar backbone

### ISSUE THREAD

**Issue by konyul** [fudan-zvg/DeepInteraction#7]
which large lidar backbone did you adopt compared to deepinteraction-base??

**Comment by konyul** [comment]
And do you need more epochs to converge deepinteraction-e compared to deepinteraction-base?? 
Thank you

**Comment by Alexander0Yang** [comment]
> which large lidar backbone did you adopt compared to deepinteraction-base??

We still use VoxelNet in DeepInteraction-e, but enlarge some hyperparameters of the lidar backbone according to the voxel size.

> And do you need more epochs to converge deepinteraction-e compared to deepinteraction-base??

No, we didn't tune the training schedule exhaustively for each model used in the ensemble version.

**Comment by konyul** [comment]
could you share the hyperparameters of the lidar backbone used to train deepinteraction-e??
thank you

**Comment by konyul** [comment]
I found the hyperparameters of the larger lidar backbone in your paper, 
Thank you for the answering!!

**Comment by Alexander0Yang** [comment]
Nice.
