### ISSUE TITLE
ImportError of localattention.so

### ISSUE THREAD

**Issue by yinjunbo** [fudan-zvg/DeepInteraction#8]
`ImportError: /mnt/data/DeepInteraction/projects/mmdet3d_plugin/models/utils/ops/locatt_ops/localattention.so: cannot open shared object file: No such file or directory
`
Thanks for your nice work.
Where is the code for compiling these ops?

**Comment by Alexander0Yang** [comment]
Hi @yinjunbo.
Thanks for your interest. The code for compiling can be found in `projects/mmdet3d_plugin/models/utils/ops/locatt_ops`.  Please refer to https://github.com/fudan-zvg/DeepInteraction/blob/main/projects/mmdet3d_plugin/models/utils/ops/locatt_ops/__init__.py#L13-15 where the path is specified.

**Comment by SISTMrL** [comment]
> Hi @yinjunbo. Thanks for your interest. The code for compiling can be found in `projects/mmdet3d_plugin/models/utils/ops/locatt_ops`. Please refer to https://github.com/fudan-zvg/DeepInteraction/blob/main/projects/mmdet3d_plugin/models/utils/ops/locatt_ops/__init__.py#L13-15 where the path is specified.

hello, how i compile the localattention.so, i can't understand what you said, could you please give more clear explaination for compile the localattention, the torch.cuda.is_available() is true for me
