### ISSUE TITLE
Install.md is lost

### ISSUE THREAD

**Issue by Lizhuoling** [fudan-zvg/DeepInteraction#9]
Hi, the install.md mentioned in the README.md seems to be lost in this repo. Meanwhile, what are the versions of mmdetection, mmcv, mmdetection3d used in this repo? I cannot start training properly due to the version issue.

**Comment by Alexander0Yang** [comment]
Thanks for the reminding! We update the [install.md](https://github.com/fudan-zvg/DeepInteraction/blob/main/install.md) and provide the environment we use in it for reference.
